### PR TITLE
Eagle-inspired colour theme for KiCAD

### PR DESCRIPTION
**Pull request by dragonmux**
I decided recently to create an eagle-inspired colour theme for KiCAD and it is as complete as I have found time to make it for now.

The theme is correct for and works well up to 6 PCB layers, after which further tweaking is needed.
I am aware that this has been regularly requested by communities such as 1BitSquared.

### CODE REVIEW

**Comment by pointhi** [comment]
Please add an entry to the README including screenshots as done for all other color-schemes. Furthermore, there is a `migrate_to_v6.py` script to generated a style file as it will be used by future KiCad versions.

**Comment by dragonmux** [comment]
This should now be done. I saw the v6 script and there shouldn't be anything I'm doing that conflicts with that script.

Are you asking me to run that script and commit the result?

**Comment by pointhi** [comment]
Yes, run the script and commit the result.

Isn't the background in Eagle white by default, for the schematic?

**Comment by dragonmux** [comment]
It's select-able.. you can use either light or dark backgrounds and as the colour choices work better for dark, and I'm a dark-theme user, I opted to provide the theme with a dark background - though we could do a light variant - I am not adverse to this.

**Comment by pointhi** [comment]
Thank you for your contribution

**Pull request merged**
